name: Scan-o-Matic CI

on: [push]

jobs:
    frontend-lint:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2

        - name: Install
          run: |
            npm install

        - name: Lint
          run: |
            npm run lint

    frontend-test:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
        - uses: browser-actions/setup-chrome@latest
        - uses: nanasess/setup-chromedriver@master

        - name: Setup Chromedriver
          run: |
            export DISPLAY=:99
            chromedriver --url-base=/wd/hub &
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

        - name: Install
          run: |
            npm install

        - name: Test
          run: |
            npm test

    frontend-build:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2

        - name: Install
          run: |
            npm install

        - name: Builds
          run: |
            npm run build

    backend-lint:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install General Dependencies
          run: |
            python3.9 -m pip install --upgrade pip
            pip install tox

        - name: Lint and Types
          run: |
            tox -e lint

    backend-mypy:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install General Dependencies
          run: |
            python3.9 -m pip install --upgrade pip
            pip install tox

        - name: Lint and Types
          run: |
            tox -e mypy

    backend-test-unit:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install General Dependencies
          run: |
            python3.9 -m pip install --upgrade pip
            pip install tox

        - name: Run unit tests
          run: |
            tox -e unit

    backend-test-integration:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install General Dependencies
          run: |
            python3.9 -m pip install --upgrade pip
            pip install tox

        - name: Run integration tests
          run: |
            tox -e integration

    backend-test-system:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install General Dependencies
          run: |
            python3.9 -m pip install --upgrade pip
            pip install tox

        - name: Run system tests
          run: |
            tox -e system

    docker-build:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2

        - name: Build
          run: |
            docker-compose build
